### PR TITLE
Sensible `repo_path` default

### PR DESCRIPTION
**Pull request by juanca**
See https://github.com/mavenlink/orbs/issues/9 for more information

### CODE REVIEW

**Comment by tjerkw** [comment]
Can we merge this?

**Comment by juanca** [comment]
It's breaking the test suite. I'm not really sure what changed. I'll see if I can take another stab at it later this week.

**Comment by juanca** [comment]
The same failure is occurring to a text change. This seems to be a change in the CircleCI infrastructure.

**Comment by juanca** [comment]
Hey @tjerkw 

I finally got around to getting a stable CI build. I am going to merge this PR and deploy a new release.

**Pull request merged**
